package com.shubhamthorat.echo.shared.ai

import kotlinx.coroutines.flow.Flow

/**
 * Interface for local document analysis using RAG (Retrieval-Augmented Generation).
 */
interface DocumentAnalyzer {
    /**
     * Ingests a document and indexes it for analysis.
     * @param documentPath Path to the document (local or URI).
     * @return A Flow representing the progress of ingestion (0.0 to 1.0).
     */
    suspend fun ingestDocument(documentPath: String): Flow<Float>

    /**
     * Analyzes the ingested document(s) based on a query.
     * @param query The user's question or prompt.
     * @return The answer generated by the local LLM.
     */
    suspend fun ask(query: String): String

    /**
     * Clears indexed data.
     */
    suspend fun clearIndex()
}

data class AnalysisResult(
    val answer: String,
    val sourceChunks: List<String>
)
